export const DESIGN_TOKENS = {
  colors: {
    canvasBg: "#FBFAF7",
    canvasGrid: "#EFEDE6",
    surfaceCard: "#FFFFFF",
    surfaceRecessed: "#F3F1EA",
    inkHairline: "#D9D5C7",
    inkHairlineStrong: "#B8B29D",
    inkPrimary: "#1B3A5C",
    inkPrimaryTint: "#E9EFF5",
    sealVerified: "#2F6844",
    sealVerifiedTint: "#EBF2EC",
    sealPending: "#9A6B1F",
    sealFlagged: "#8C2F2F",
    signalCameraLive: "#1B3A5C",
    inkText: "#3D3A31",
    inkMuted: "#8A8571",
  },
  typography: {
    fontDisplay: "var(--font-space-grotesk), sans-serif",
    fontBody: "var(--font-plex-sans), sans-serif",
    fontMono: "var(--font-plex-mono), monospace",
  },
  borders: {
    hairline: "1px solid #D9D5C7",
    hairlineStrong: "1px solid #B8B29D",
    dashedHairline: "1px dashed #D9D5C7",
  },
};

export const INITIAL_SKILLS = [
  { id: "javascript", name: "JavaScript", category: "languages" as const, description: "Core ES6+, closures, async/await, DOM APIs, and execution model" },
  { id: "react", name: "React", category: "frontend" as const, description: "Hooks, reconciliation, component state, context, performance, and modern SSR" },
  { id: "typescript", name: "TypeScript", category: "languages" as const, description: "Type inference, generics, utility types, narrowing, and discriminated unions" },
  { id: "python", name: "Python", category: "languages" as const, description: "Data structures, generators, OOP, decorators, and asynchronous programming" },
  { id: "sql", name: "SQL", category: "database" as const, description: "Joins, grouping, window functions, indexing, normalization, and query optimization" },
  { id: "nextjs", name: "Next.js", category: "frontend" as const, description: "App Router, Server Components, Route Handlers, caching, and Server Actions" },
  { id: "nodejs", name: "Node.js", category: "backend" as const, description: "Event loop, streams, buffers, Express, and microservices architecture" },
  { id: "solidity", name: "Solidity", category: "languages" as const, description: "Smart contracts, EVM execution, ERC standards, reentrancy guards, and gas optimization" },
  { id: "pytorch", name: "PyTorch", category: "backend" as const, description: "Tensor operations, autograd, model training loops, neural architectures, and inference" },
  { id: "go", name: "Go", category: "languages" as const, description: "Concurrency primitives, channels, goroutines, memory management, and high-throughput networking" },
  { id: "docker", name: "Docker", category: "devops" as const, description: "Container lifecycle, multi-stage builds, rootless execution, and orchestration" },
  { id: "linux", name: "Linux", category: "devops" as const, description: "POSIX system calls, process scheduling, eBPF telemetry, shell automation, and networking" },
  { id: "rust", name: "Rust", category: "languages" as const, description: "Borrow checker, lifetimes, fearless concurrency, zero-cost abstractions, and systems programming" },
];
